[package]
name = "sushi"
description="A simple but customizable static site generator / blog generator"
version = "0.2.0"
edition = "2021"
license="LGPL-3.0"
keywords=["static", "site", "generator", "blog"]
categories=["command-line-utilities"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name="ssushi"
path="src/main.rs"

[dependencies]
liquid = "0.24.0"
serde = "1.0"
serde_yaml = "0.8"
subprocess = "0.2.8"
lazy_static = "1.4.0"
itertools = "0.10.3"
log = "0.4.14"
simple_logger = "2.1.0"
clap = { version = "3.1.6", features = ["derive"] }
chrono = "0.4"
directories = "4.0.1"
regex = "1.5.5"
